import {
  LogIn,
  LogOut,
  FolderPlus,
  DollarSign,
  Percent,
  DoorOpen,
  DoorClosed,
  AtSign,
  MessageSquareText,
  Clock,
  MessageSquareWarning,
  Bell,
  MessageCircle,
  MessageCircleMore,
  Handshake,
  CheckCircle2,
  Archive,
  FileCheck2,
  Heart,
  UserPlus,
  ScrollText,
  Building2,
  BadgeCheck,
  BadgeX,
  UserPlus2,
  Mail,
  MailCheck,
  MailX,
  UserMinus,
  Shuffle,
  Crown,
  CalendarPlus,
  CalendarCheck2,
  CalendarX2,
  Users,
  ShieldCheck,
  ShieldPlus,
  type LucideIcon,
} from "lucide-react";
import type { NotificationType } from "@prisma/client";

export const NOTIFICATION_TYPE_META: Record<NotificationType, { icon: LucideIcon }> = {
  CHECK_IN: { icon: LogIn },
  CHECK_OUT: { icon: LogOut },
  PROJECT_ASSIGNED: { icon: FolderPlus },
  GMV_ENTERED: { icon: DollarSign },
  COMMISSION_GENERATED: { icon: Percent },
  SPACE_STARTED: { icon: DoorOpen },
  SPACE_FINISHED: { icon: DoorClosed },
  MENTION: { icon: AtSign },
  COMMENT: { icon: MessageSquareText },
  DEADLINE: { icon: Clock },
  FEEDBACK_SUBMITTED: { icon: MessageSquareWarning },
  SYSTEM: { icon: Bell },
  COLLAB_MESSAGE_RECEIVED: { icon: MessageCircle },
  DIRECT_MESSAGE_RECEIVED: { icon: MessageCircleMore },
  COLLAB_APPLICATION_RECEIVED: { icon: Handshake },
  COLLAB_APPLICATION_ACCEPTED: { icon: CheckCircle2 },
  COLLAB_POST_CLOSED: { icon: Archive },
  MEMBERSHIP_APPLICATION_RECEIVED: { icon: FileCheck2 },
  LIKE: { icon: Heart },
  NEW_FOLLOWER: { icon: UserPlus },
  LEGAL_DOCUMENT_UPDATED: { icon: ScrollText },
  AGENCY_REQUEST_RECEIVED: { icon: Building2 },
  AGENCY_REQUEST_APPROVED: { icon: BadgeCheck },
  AGENCY_REQUEST_REJECTED: { icon: BadgeX },
  AGENCY_ACCESS_REQUESTED: { icon: UserPlus2 },
  AGENCY_ACCESS_APPROVED: { icon: BadgeCheck },
  AGENCY_ACCESS_REJECTED: { icon: BadgeX },
  TEAM_INVITATION_SENT: { icon: Mail },
  TEAM_INVITATION_ACCEPTED: { icon: MailCheck },
  TEAM_INVITATION_DECLINED: { icon: MailX },
  TEAM_INVITATION_REVOKED: { icon: MailX },
  TEAM_ROLE_CHANGED: { icon: Shuffle },
  TEAM_OWNERSHIP_TRANSFERRED: { icon: Crown },
  TEAM_MEMBER_REMOVED: { icon: UserMinus },
  EVENT_PROPOSAL_SUBMITTED: { icon: CalendarPlus },
  EVENT_APPROVED: { icon: CalendarCheck2 },
  EVENT_REJECTED: { icon: CalendarX2 },
  EVENT_CHANGES_REQUESTED: { icon: MessageSquareWarning },
  EVENT_CAPACITY_REACHED: { icon: Users },
  EVENT_CANCELLED: { icon: CalendarX2 },
  EVENT_WAITLIST_PROMOTED: { icon: CalendarCheck2 },
  ADMIN_ACCESS_GRANTED: { icon: ShieldCheck },
  SUPER_ADMIN_ACCESS_GRANTED: { icon: ShieldPlus },
};
