import type { TemplateName } from "@/lib/email/email-types";
import type { EmailCategory, EmailStatus } from "@prisma/client";

/**
 * Single source of truth for "which of the 11 Email Center categories does
 * this template belong to" — derived automatically at send time in
 * email-service.ts, so no call site ever has to think about category.
 * Mirrors the backfill CASE statement in the
 * 20260728190000_email_center_fields migration (keep both in sync if a
 * template's category ever changes).
 */
export const TEMPLATE_CATEGORY: Record<TemplateName, EmailCategory> = {
  welcome: "AUTHENTICATION",
  password_reset: "AUTHENTICATION",
  verify_email: "AUTHENTICATION",
  password_changed: "AUTHENTICATION",
  email_changed: "AUTHENTICATION",
  org_invitation: "ADMIN",
  reservation_confirmed: "SPACES",
  visitor_arrival: "ADMIN",
  commission_notification: "BILLING",
  membership_approved: "MEMBERSHIP",
  membership_denied: "MEMBERSHIP",
  announcement: "MARKETING",
  application_received: "MEMBERSHIP",
  application_approved: "MEMBERSHIP",
  application_rejected: "MEMBERSHIP",
  membership_activated: "MEMBERSHIP",
  trial_ending_soon: "BILLING",
  subscription_renewal: "BILLING",
  payment_failed: "BILLING",
  new_like: "COMMUNITY",
  new_comment: "COMMUNITY",
  mention: "COMMUNITY",
  new_follower: "COMMUNITY",
  conversation_invitation: "MESSAGING",
  new_direct_message: "MESSAGING",
  new_group_message: "MESSAGING",
  brand_invitation: "PROJECTS",
  collaboration_request: "PROJECTS",
  project_approved: "PROJECTS",
  project_completed: "PROJECTS",
  reservation_reminder: "SPACES",
  reservation_cancelled: "SPACES",
  event_registration: "EVENTS",
  event_reminder: "EVENTS",
  event_starting_soon: "EVENTS",
  event_approved: "EVENTS",
  event_rejected: "EVENTS",
  event_changes_requested: "EVENTS",
  event_cancelled: "EVENTS",
  new_membership_application_admin: "ADMIN",
  new_creator_joined_admin: "ADMIN",
  daily_admin_summary: "ADMIN",
  critical_system_alert: "SYSTEM",
  legal_document_updated: "ADMIN",
  agency_request_received: "ADMIN",
  agency_request_approved: "MEMBERSHIP",
  agency_request_rejected: "MEMBERSHIP",
  agency_access_requested: "ADMIN",
  agency_access_approved: "MEMBERSHIP",
  agency_access_rejected: "MEMBERSHIP",
  agency_team_activity: "ADMIN",
  welcome_newsletter: "MEMBERSHIP",
} satisfies Record<TemplateName, EmailCategory>;

/** One-liners for the Email Templates catalog page. */
export const TEMPLATE_DESCRIPTIONS: Record<TemplateName, string> = {
  welcome: "Sent when a new member's account is provisioned — login link, temp password, QR badge.",
  password_reset: "Sent when a member requests a password reset link.",
  verify_email: "Sent to confirm a newly signed-up member's email address.",
  password_changed: "Confirmation sent after a member's password is changed.",
  email_changed: "Confirmation sent to a member's new address after an email change.",
  org_invitation: "Sent when an admin invites someone to join the organization.",
  reservation_confirmed: "Sent when a space booking is confirmed.",
  visitor_arrival: "Sent to front-desk staff when a visitor checks in via kiosk.",
  commission_notification: "Sent when a commission is earned or paid out.",
  membership_approved: "Sent when a pending membership application is approved.",
  membership_denied: "Sent when a pending membership application is denied.",
  announcement: "Ad-hoc broadcast sent by an admin to selected members.",
  application_received: "Sent immediately after a public membership application is submitted.",
  application_approved: "Sent when an admin approves a membership application (onboarding email).",
  application_rejected: "Sent when an admin rejects a membership application.",
  membership_activated: "Sent when a trial subscription auto-converts to an active membership.",
  trial_ending_soon: "Sent a few days before a trial subscription ends.",
  subscription_renewal: "Sent when a membership subscription renews for a new billing period.",
  payment_failed: "Sent when a subscription payment fails and the account moves to past-due.",
  new_like: "Sent when someone likes a member's Collab Hub post.",
  new_comment: "Sent when someone comments on a member's Collab Hub post.",
  mention: "Sent when a member is @mentioned in a comment.",
  new_follower: "Sent when a member gains a new follower.",
  conversation_invitation: "Sent on the first message of a brand-new direct or group conversation.",
  new_direct_message: "Sent for new messages in an existing 1:1 conversation.",
  new_group_message: "Sent for new messages in an existing group conversation.",
  brand_invitation: "Sent when a brand is invited to collaborate on a project.",
  collaboration_request: "Sent when a member requests to join a project.",
  project_approved: "Sent to assignees when a project moves from planning to active.",
  project_completed: "Sent to assignees when a project is marked complete.",
  reservation_reminder: "Sent ~1 hour before a confirmed space reservation.",
  reservation_cancelled: "Sent when a space reservation is cancelled.",
  event_registration: "Sent when a member RSVPs yes to an event.",
  event_reminder: "Sent ~24 hours before an event a member registered for.",
  event_starting_soon: "Sent ~1 hour before an event a member registered for.",
  event_approved: "Sent to the host when an admin approves and publishes their event proposal.",
  event_rejected: "Sent to the host when an admin declines their event proposal.",
  event_changes_requested: "Sent to the host when an admin asks for changes before a proposal can be published.",
  event_cancelled: "Sent to every registered attendee when a published event is cancelled.",
  new_membership_application_admin: "Sent to admins when a new membership application comes in.",
  new_creator_joined_admin: "Sent to admins when a new creator member joins.",
  daily_admin_summary: "Daily digest of prior-day activity, sent to admins.",
  critical_system_alert: "Sent to admins when a critical email (auth/billing) exhausts every retry.",
  legal_document_updated: "Sent to all affected members when an admin publishes a major legal document update.",
  agency_request_received: "Sent to an agency when a creator manually enters their Agency ID and requests to connect.",
  agency_request_approved: "Sent to a creator when the agency they requested approves the connection.",
  agency_request_rejected: "Sent to a creator when the agency they requested declines the connection.",
  agency_access_requested: "Sent to an existing agency's admins when someone requests to join their team instead of registering a duplicate agency.",
  agency_access_approved: "Sent to a user when the existing agency they requested to join approves their access.",
  agency_access_rejected: "Sent to a user when the existing agency they requested to join declines their access.",
  agency_team_activity: "Generic Team Management notification — invitations, role changes, ownership transfers, and removals.",
  welcome_newsletter: "Sent separately from the account/access email when a membership application is approved — the CreatorHub360 welcome newsletter artwork, informational only (no login details).",
};

export const EMAIL_CATEGORY_LABELS: Record<EmailCategory, string> = {
  AUTHENTICATION: "Authentication",
  MEMBERSHIP: "Membership",
  COMMUNITY: "Community",
  MESSAGING: "Messaging",
  PROJECTS: "Projects",
  SPACES: "Spaces",
  EVENTS: "Events",
  ADMIN: "Admin",
  BILLING: "Billing",
  MARKETING: "Marketing",
  SYSTEM: "System",
};

export const EMAIL_STATUS_LABELS: Record<EmailStatus, string> = {
  QUEUED: "Queued",
  SENT: "Delivered",
  RETRYING: "Processing",
  FAILED: "Failed",
  DELIVERED: "Delivered",
  OPENED: "Opened",
  CLICKED: "Clicked",
  BOUNCED: "Bounced",
  COMPLAINED: "Complained",
};
