import type { ContentCategory } from "@prisma/client";

export const contentCategoryValues = [
  "FITNESS",
  "GAMING",
  "FASHION",
  "BEAUTY",
  "LIFESTYLE",
  "TECH",
  "FOOD",
  "TRAVEL",
  "COMEDY",
  "MUSIC",
  "DANCE",
  "BUSINESS",
  "ENTREPRENEURSHIP",
  "EDUCATION",
  "PHOTOGRAPHY",
  "MODELING",
  "SPORTS",
  "AUTOMOTIVE",
  "PARENTING",
  "PETS",
  "FINANCE",
  "LUXURY",
  "HEALTH",
  "ART",
  "DIY",
  "STREAMING",
  "VLOGS",
  "PODCASTS",
] as const;

export const CONTENT_CATEGORY_LABELS: Record<ContentCategory, string> = {
  FITNESS: "Fitness",
  GAMING: "Gaming",
  FASHION: "Fashion",
  BEAUTY: "Beauty",
  LIFESTYLE: "Lifestyle",
  TECH: "Tech",
  FOOD: "Food",
  TRAVEL: "Travel",
  COMEDY: "Comedy",
  MUSIC: "Music",
  DANCE: "Dance",
  BUSINESS: "Business",
  ENTREPRENEURSHIP: "Entrepreneurship",
  EDUCATION: "Education",
  PHOTOGRAPHY: "Photography",
  MODELING: "Modeling",
  SPORTS: "Sports",
  AUTOMOTIVE: "Automotive",
  PARENTING: "Parenting",
  PETS: "Pets",
  FINANCE: "Finance",
  LUXURY: "Luxury",
  HEALTH: "Health",
  ART: "Art",
  DIY: "DIY",
  STREAMING: "Streaming",
  VLOGS: "Vlogs",
  PODCASTS: "Podcasts",
};
