-- Rename MANAGEMENT -> BUSINESS_DEVELOPMENT, add ENTERTAINMENT and INVESTOR
ALTER TYPE "MemberRole" RENAME VALUE 'MANAGEMENT' TO 'BUSINESS_DEVELOPMENT';
ALTER TYPE "MemberRole" ADD VALUE 'ENTERTAINMENT';
ALTER TYPE "MemberRole" ADD VALUE 'INVESTOR';
